name: Mayhem CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # checkout repository
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Login to docker
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Install Docker Scout
      run: curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s --

    - name: Install mdsbom
      run: curl -sSL https://app.mayhem.security/cli/mdsbom/linux/latest/mdsbom.deb -O && sudo dpkg -i mdsbom.deb && sudo usermod -aG mdsbom $USER

    - name: MDSBOM login
      run: mdsbom login https://app.mayhem.security  ${{ secrets.MAYHEM_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push the target image
      id: push
      uses: docker/build-push-action@v5
      with:
        context: car
        file: car/Dockerfile
        push: true
        # tag the image with the commit SHA
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Start Code analysis
      uses: forallsecure/mcode-action@v1
      with:
        mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
        owner: forallsecure
        args: -f car/Mayhemfile --image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        sarif-output: code.sarif

    - name: Upload SARIF file(s)
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: code.sarif

    - name: Bring up the API
      run: docker compose up -d

    - name: Wait for the API to be up
      run: bash -c 'while ! curl -s http://localhost:8000/openapi.json; do sleep 1; done'

    - name: Start API analysis
      uses: forallsecure/mapi-action@v1
      continue-on-error: true
      with:
        mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
        target: forallsecure/gps-telemetry/api
        api-url: http://localhost:8000
        api-spec: http://localhost:8000/openapi.json
        sarif-report: api.sarif
        args: -f api/Mayhemfile --duration 300 --url http://localhost:8000/openapi.json
        sarif-output: sarif

    - name: Upload SARIF file(s)
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: api.sarif

    - name: Run Dynamic SBOM scan
      run: mdsbom scout redis:alpine --sca-report-out dsbom.sarif --sca-summary-csv dsbom.json --workspace forallsecure

      # run the following whtn the dsbom.sarif file is generated
    - name: Patch docker scout SARIF report for CodeQL
      run : |
        if [ -f dsbom.sarif ]; then jq 'walk(if type == "object" and has("startLine") and .startLine == 0 then .startLine = 1 else . end |
            if type == "object" and has("endLine") and .endLine == 0 then .endLine = 1 else . end |
            if type == "object" and has("endColumn") and .endColumn == 0 then .endColumn = 1 else . end |
            if type == "object" and has("startColumn") and .startColumn == 0 then .startColumn = 1 else . end)' dsbom.sarif > dsbom-patched.sarif; fi
        touch dsbom-patched.sarif


    # upload artifact of the dsbom-patched.sarif file
    - name: Upload SARIF file(s)
      uses: actions/upload-artifact@v2
      with:
        name: dsbom-patched-sarif
        path: dsbom-patched.sarif

    # - name: Upload SARIF file(s)
    #   uses: github/codeql-action/upload-sarif@v2
    #   with:
    #     sarif_file: dsbom-patched.sarif
